# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Wojciech Polak
#
# Generated by scripts/render-homebrew-formula.mjs in wojciechpolak/dud and
# rewritten in full by that repository's release workflow. Edit the renderer,
# not this file.

class Dud < Formula
  desc "Discreet upload / download over dead drops and paired peers"
  homepage "https://github.com/wojciechpolak/dud"
  url "https://github.com/wojciechpolak/dud/archive/refs/tags/v2.4.0.tar.gz"
  sha256 "d84bd79918fb2f1a60e61ce56da65d7f947419df39639713097ab33601120f89"
  license "MIT"

  depends_on "go" => :build
  depends_on "age"
  depends_on "git"
  depends_on "qrencode"

  def install
    cd "client" do
      ENV["CGO_ENABLED"] = "0"
      ldflags = "-buildid= -X main.version=#{version}"
      system "go", "build", *std_go_args(output: bin/"dud", ldflags: ldflags), "./cmd/dud"
    end
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/dud --version").strip
  end
end
